name: real_world
task_name: pour_water

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [8]

env_runner:
  _target_: null  # !! implementing customized class for real robot deployment
  task_name: ${task.task_name}

  has_lang_emb: False
  has_stage_emb: False
  enable_stage: False
  pose_estimation_wrapper: null

dataset:
  _target_: diffusion_policy_3d.dataset.rlbench_dataset.RLBenchDataset
  root_dir: /tmp/pour_water/

  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}'}
  pad_after: ${eval:'${n_action_steps}'}
  seed: 42
  val_ratio: 0.1
  max_train_episodes: 100
  has_lang_emb: False
  has_stage_emb: False
  random_aug: True
  symmetric_axis: null
  symmetric_theta_start: null
  symmetric_theta_end: null
  symmetric_theta_step: null
